Core/urls.py
from django.urls import path
from .views import InboxView, ProfileView


urlpatterns = [
    path('', InboxView.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

Task/urls.py
from django.urls import path
from .views import AssignedTaskListView, BinListView, ForwardFormView, ForwardTaskListView, InboxListView, SendTaskListView, TaskCreateView, TaskDetailView, toggle_action_status, toggle_action_status_forward



urlpatterns = [
    path('inbox/', InboxListView.as_view(), name='inbox'),
    path('send_task/', SendTaskListView.as_view(), name='send_task'),
    path('create/', TaskCreateView.as_view(), name='create'),
    path('bin/', BinListView.as_view(), name='bin'),
    path('task_detail/<int:pk>', TaskDetailView.as_view(), name='task_detail'),

    path('forwarded/', ForwardTaskListView.as_view(), name='forwarded'),
    path('assigned/', AssignedTaskListView.as_view(), name='assigned'),
    path('task_forward/<int:pk>', ForwardFormView.as_view(), name='task_forward'),


    path('toggle_action_status/', toggle_action_status, name='toggle_action_status'),
    path('toggle_action_status_forward/', toggle_action_status_forward, name='toggle_action_status_forward'),

]

TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Account.urls")),
    path('', include("Core.urls")),
    path('', include("Task.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task/models.py
from django.db import models
from services.mixins import DateMixin
from Account.models import Account
from services.uploader import Uploader
from ckeditor.fields import RichTextField




class TaskCategory(DateMixin):
    category_title = models.CharField(max_length=255)

    def __str__(self):
        return self.category_title

    class Meta:
        verbose_name = 'Task Category'
        verbose_name_plural = 'Task Category'


class TaskToMembersAction(DateMixin):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='task_to_member_action')
    to_member = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='task_to_members', null=True, blank=True)
    task_member_is_read = models.BooleanField(default=False)
    task_member_is_pin = models.BooleanField(default=False)
    task_member_is_deleted = models.BooleanField(default=False)
    bin_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.task.task_title} members : {self.to_member}"

    class Meta:
        verbose_name = 'Task to Members Action'
        verbose_name_plural = 'Task to Members Action'


class TaskCCMembersAction(DateMixin):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='task_cc_member_action')
    cc_member = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='task_cc_members', null=True, blank=True)
    task_member_is_read = models.BooleanField(default=False)
    task_member_is_pin = models.BooleanField(default=False)
    task_member_is_deleted = models.BooleanField(default=False)
    bin_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.task.task_title} members : {self.cc_member}"


    class Meta:
        verbose_name = 'Task cc Members Action'
        verbose_name_plural = 'Task cc Members Action'


class Task(DateMixin):
    status_title = (
        ('Working', 'Working'),
        ('Canceled', 'Canceled'),
        ('Done', 'Done')
    )
    importance_level_status = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High')
    )
    task_title = models.CharField(max_length=255)
    task_image = models.ImageField(upload_to=Uploader.task_image, max_length=255, null=True, blank=True)
    task_content = RichTextField()
    task_author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='task_author')
    task_status = models.CharField(max_length=20, choices=status_title, null=True, blank=True) # status create olan qoyulsun yoxsa edit olanda
    task_importance_level = models.CharField(max_length=20, choices=importance_level_status)
    task_deadline = models.DateTimeField()
    task_author_is_deleted = models.BooleanField(default=False)
    task_category = models.ForeignKey(TaskCategory, on_delete=models.CASCADE, related_name='task_category')
    bin_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.task_title

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Task'


class TaskActionLog(DateMixin):
    log_author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='log_author')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='log_task')
    old_status = models.CharField(max_length=20, choices=Task.status_title, null=True, blank=True)
    new_status = models.CharField(max_length=20, choices=Task.status_title, null=True, blank=True)

    def __str__(self):
        return f"{self.log_author.first_name} {self.log_author.last_name} - {self.task.task_title}"

    class Meta:
        verbose_name = 'Task Action Log'
        verbose_name_plural = 'Task Action Log'


class ForwardTask(DateMixin):
    forward_author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='author_forward')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='task_forward')
    forward_author_content = RichTextField(null=True, blank=True)
    forward_author_task_is_deleted = models.BooleanField(default=False)
    bin_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.forward_author.get_full_name()} - {self.task.task_title}"

    class Meta:
        verbose_name = 'Forward Task'
        verbose_name_plural = 'Forward Task'


class ForwardedToWhom(DateMixin):
    whom = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='whom')
    forward_task = models.ForeignKey(ForwardTask, on_delete=models.CASCADE, related_name='forward_task')
    whom_is_read = models.BooleanField(default=False)
    whom_is_pin = models.BooleanField(default=False)
    whom_is_deleted = models.BooleanField(default=False)
    bin_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.whom.get_full_name()

    class Meta:
        verbose_name = 'Forwarded To Whom'
        verbose_name_plural = 'Forwarded To Whom'

Task/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from Core.models import MemberTaskStatistic
from .models import ForwardTask, ForwardedToWhom, Task, TaskActionLog, TaskCCMembersAction, TaskToMembersAction
from .forms import ForwardForm, TaskDetailForm, TaskForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Q, Case, When, Value, BooleanField
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime


class InboxListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'inbox.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        to_task_search = self.request.GET.get('to_task_search', '')
        cc_task_search = self.request.GET.get('cc_task_search', '')

        to_tasks = Task.objects.order_by('-created_at').filter(
                task_to_member_action__to_member=self.request.user,
                task_to_member_action__task_member_is_pin = False,
                task_to_member_action__task_member_is_deleted = False,
                task_to_member_action__bin_deleted = False
            ).exclude(task_author=self.request.user).distinct().annotate(
            is_view=Case(
                When(task_to_member_action__to_member=self.request.user, task_to_member_action__task_member_is_read=True, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            )
        )

        to_tasks_pinned = Task.objects.order_by('-created_at').filter(
                task_to_member_action__to_member=self.request.user,
                task_to_member_action__task_member_is_pin = True,
                task_to_member_action__task_member_is_deleted = False,
                task_to_member_action__bin_deleted = False
            ).exclude(task_author=self.request.user).distinct().annotate(
            is_view=Case(
                When(task_to_member_action__to_member=self.request.user, task_to_member_action__task_member_is_read=True, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            )
        )

        cc_tasks = Task.objects.order_by('-created_at').filter(
            task_cc_member_action__cc_member=self.request.user,
            task_cc_member_action__task_member_is_pin = False,
            task_cc_member_action__task_member_is_deleted = False,
            task_cc_member_action__bin_deleted = False
        ).exclude(task_author=self.request.user).distinct().annotate(
            is_view=Case(
                When(task_cc_member_action__cc_member=self.request.user, task_cc_member_action__task_member_is_read=True, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            )
        )

        cc_tasks_pinned = Task.objects.order_by('-created_at').filter(
            task_cc_member_action__cc_member=self.request.user,
            task_cc_member_action__task_member_is_pin = True,
            task_cc_member_action__task_member_is_deleted = False,
            task_cc_member_action__bin_deleted = False
        ).exclude(task_author=self.request.user).distinct().annotate(
            is_view=Case(
                When(task_cc_member_action__cc_member=self.request.user, task_cc_member_action__task_member_is_read=True, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            )
        )

        if to_task_search:
            to_tasks = to_tasks.filter(
                 Q(task_title__icontains=to_task_search)
                 | Q(task_importance_level__icontains=to_task_search)
                 | Q(task_status__icontains=to_task_search)
                 | Q(task_author__first_name__icontains=to_task_search)
                 | Q(task_author__last_name__icontains=to_task_search)
                 | Q(task_author__department__title__icontains=to_task_search)
                 | Q(task_author__email__icontains=to_task_search)
                 | Q(task_author__status__icontains=to_task_search)
                 | Q(task_category__category_title__icontains=to_task_search)
                 )
            to_tasks_pinned = to_tasks_pinned.filter(
                 Q(task_title__icontains=to_task_search)
                 | Q(task_importance_level__icontains=to_task_search)
                 | Q(task_status__icontains=to_task_search)
                 | Q(task_author__first_name__icontains=to_task_search)
                 | Q(task_author__last_name__icontains=to_task_search)
                 | Q(task_author__department__title__icontains=to_task_search)
                 | Q(task_author__email__icontains=to_task_search)
                 | Q(task_author__status__icontains=to_task_search)
                 | Q(task_category__category_title__icontains=to_task_search)
                 )
        elif cc_task_search:
            cc_tasks = cc_tasks.filter(
                   Q(task_title__icontains=cc_task_search)
                 | Q(task_importance_level__icontains=cc_task_search)
                 | Q(task_status__icontains=cc_task_search)
                 | Q(task_author__first_name__icontains=cc_task_search)
                 | Q(task_author__last_name__icontains=cc_task_search)
                 | Q(task_author__department__title__icontains=cc_task_search)
                 | Q(task_author__email__icontains=cc_task_search)
                 | Q(task_author__status__icontains=cc_task_search)
                 | Q(task_category__category_title__icontains=cc_task_search)
            )
            cc_tasks_pinned = cc_tasks_pinned.filter(
                   Q(task_title__icontains=cc_task_search)
                 | Q(task_importance_level__icontains=cc_task_search)
                 | Q(task_status__icontains=cc_task_search)
                 | Q(task_author__first_name__icontains=cc_task_search)
                 | Q(task_author__last_name__icontains=cc_task_search)
                 | Q(task_author__department__title__icontains=cc_task_search)
                 | Q(task_author__email__icontains=cc_task_search)
                 | Q(task_author__status__icontains=cc_task_search)
                 | Q(task_category__category_title__icontains=cc_task_search)
            )

        # Pagination to_tasks
        to_task_search_page = self.request.GET.get('to_task_search_page')
        paginator = Paginator(to_tasks, self.paginate_by)

        try:
            to_tasks = paginator.page(to_task_search_page)
        except PageNotAnInteger:
            to_tasks = paginator.page(1)
        except EmptyPage:
            to_tasks = paginator.page(paginator.num_pages)

        # Pagination cc_tasks
        cc_task_search_page = self.request.GET.get('cc_task_search_page')
        paginator = Paginator(cc_tasks, self.paginate_by)

        try:
            cc_tasks = paginator.page(cc_task_search_page)
        except PageNotAnInteger:
            cc_tasks = paginator.page(1)
        except EmptyPage:
            cc_tasks = paginator.page(paginator.num_pages)


        context['to_tasks'] = to_tasks
        context['cc_tasks'] = cc_tasks
        context['to_tasks_pinned'] = to_tasks_pinned
        context['cc_tasks_pinned'] = cc_tasks_pinned

        return context


class SendTaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'send_task.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = Task.objects.filter(task_author=self.request.user, task_author_is_deleted=False, bin_deleted=False).order_by('-created_at').all()

        search = self.request.GET.get('search', '')


        if search:
            tasks = tasks.filter(
                 Q(task_title__icontains=search)
                 | Q(task_importance_level__icontains=search)
                 | Q(task_status__icontains=search)
                 | Q(task_author__first_name__icontains=search)
                 | Q(task_author__last_name__icontains=search)
                 | Q(task_author__department__title__icontains=search)
                 | Q(task_author__email__icontains=search)
                 | Q(task_author__status__icontains=search)
                 | Q(task_category__category_title__icontains=search)
                 )

        # Pagination cc_tasks
        page = self.request.GET.get('page')
        paginator = Paginator(tasks, self.paginate_by)

        try:
            tasks = paginator.page(page)
        except PageNotAnInteger:
            tasks = paginator.page(1)
        except EmptyPage:
            tasks = paginator.page(paginator.num_pages)

        context["tasks"] = tasks

        return context


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'create_task.html'
    success_url = reverse_lazy('create')

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user  # Pass the current user to the form
        return kwargs

    def form_valid(self, form):
        # Set the task_author to the current user before saving
        form.instance.task_author = self.request.user

        try:
            member_statistic = MemberTaskStatistic.objects.get(member=self.request.user, status=True)
        except MemberTaskStatistic.DoesNotExist:
            member_statistic = None

        if member_statistic:
            if  member_statistic.created_at.date() != datetime.now().date():
                member_statistic.status = False
                MemberTaskStatistic.objects.create(
                    member=self.request.user,
                    sent_task_count=1,

Task/templates/task-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Task Detail</h6>
              </div>
              {% include "messages.html" %}
            </div>
            <div class="card-body px-0 pb-2">

              <div class="row">
                <div class="row">

                  <div class="col-12 col-xl-4">
                    <div class="card card-plain h-100">
                      <div class="card-header pb-0 p-3">
                        <h6 class="mb-0">Task Information</h6>
                      </div>
                      <div class="card-body p-3">
                        <ul class="list-group">
                          <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2 pt-0">
                            <div class="avatar me-3">
                              <img src="{% if editTask.task_author.image %}{{ editTask.task_author.image.url }}{% else %}#{% endif %}" alt="{{ editTask.task_author.first_name }} {{ editTask.task_author.last_name }}" width="50px" height="50px" style="object-fit: cover;" class="border-radius-lg shadow">
                            </div>
                            <div class="d-flex align-items-start flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ editTask.task_author.first_name|capfirst }} {{ editTask.task_author.last_name|capfirst }}</h6>
                              <p class="mb-0 text-xs">{{ editTask.task_author.department.title|capfirst }} / {{ editTask.task_author.status|capfirst }}</p>
                              <p class="mb-0 text-xs"><i>{{ editTask.task_author.email }}</i></p>
                            </div>
                          </li>
                          <li class="list-group-item border-0 ps-0 text-sm font-weight-bolder"><strong class="text-dark">Task Title:</strong>
                            &nbsp; {{ editTask.task_title|capfirst }}</li>
                          <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Status:</strong>
                            &nbsp;
                            <span class="{% if editTask.task_status == 'Working' %}text-info{% elif editTask.task_status == 'Canceled' %}text-danger{% elif editTask.task_status == 'Done' %}text-success{% endif %}">
                              {{ editTask.task_status|capfirst }}
                            </span>
                          </li>
                          <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Importance Status:</strong>
                            &nbsp;
                            <span class="{% if editTask.task_importance_level == 'Medium' %}text-info{% elif editTask.task_importance_level == 'High' %}text-danger{% elif editTask.task_importance_level == 'Low' %}text-success{% endif %}">
                              {{ editTask.task_importance_level|capfirst }}
                            </span>
                          </li>
                          <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Send date:</strong>
                            &nbsp; {{ editTask.created_at|date:"M j, Y, H:i" }}</li>
                          <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Deadline:</strong>
                            &nbsp; {{ editTask.task_deadline|date:"M j, Y, H:i" }}</li>
                          <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Task Category:</strong>
                            &nbsp; {{ editTask.task_category.category_title|capfirst }}</li>
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="col-12 col-xl-8">
                    <div class="card card-plain h-100">
                      <div class="card-header pb-0 p-3">
                        <div class="row">
                          <div class="col-md-8 d-flex align-items-center">
                            <h6 class="mb-0">Task Content</h6>
                          </div>
                          <div class="col-md-4 text-end">
                            <a href="{% url 'task_forward' editTask.pk %}" class="d-flex justify-content-end align-items-center">Forward
                              <i class="material-icons opacity-10" data-bs-toggle="tooltip"
                                data-bs-placement="top" title="Forward">forward</i>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div class="card-body p-3">
                        <p class="text-sm">
                          {{ editTask.task_content|safe }}
                        </p>
                        <hr class="horizontal gray-light my-4">
                        {% if editTask.task_image %}
                          <img src="{{ editTask.task_image.url }}" width="750px" height="400px" style="object-fit: contain;" alt="">
                        {% endif %}
                      </div>
                    </div>
                  </div>

                  <div class="col-12 col-xl-4">
                    <div class="card card-plain h-100">
                      <div class="card-header pb-0 p-3">
                        <h6 class="mb-0">To Members</h6>
                      </div>
                      <div class="card-body p-3">
                        <ul class="list-group">
                          {% for action in to_members_actions %}
                            <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2">
                              <div class="avatar me-3">
                                <img src="{% if action.to_member.image %}{{ action.to_member.image.url }}{% else %}{% static 'img/kal-visuals-square.jpg' %}{% endif %}" alt="{{ action.to_member.get_full_name|capfirst }}" width="50px" height="50px" style="object-fit: cover;" class="border-radius-lg shadow">
                              </div>
                              <div class="d-flex align-items-start flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ action.to_member.get_full_name|capfirst }}.</h6>
                                <p class="mb-0 text-xs">
                                  {% if action.to_member.department.title %}{{ action.to_member.department.title|capfirst }} / {% endif %}{% if action.to_member.status %}{{ action.to_member.status|capfirst }}{% endif %}
                                </p>
                              </div>
                            </li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="col-12 col-xl-4">
                    <div class="card card-plain h-100">
                      <div class="card-header pb-0 p-3">
                        <h6 class="mb-0">CC Members</h6>
                      </div>
                      <div class="card-body p-3">
                        <ul class="list-group">
                          {% for action in cc_members_actions %}
                            <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2">
                              <div class="avatar me-3">
                                <img src="{% if action.cc_member.image %}{{ action.cc_member.image.url }}{% else %}{% static 'img/kal-visuals-square.jpg' %}{% endif %}" alt="{{ action.cc_member.get_full_name|capfirst }}" width="50px" height="50px" style="object-fit: cover;" class="border-radius-lg shadow">
                              </div>
                              <div class="d-flex align-items-start flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ action.cc_member.get_full_name|capfirst }}.</h6>
                                <p class="mb-0 text-xs">
                                  {% if action.cc_member.department.title %}{{ action.cc_member.department.title|capfirst }} / {% endif %}{% if action.cc_member.status %}{{ action.cc_member.status|capfirst }}{% endif %}
                                </p>
                              </div>
                            </li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="col-12 col-xl-4">
                    <div class="card card-plain h-100">
                      <div class="card-header pb-0 p-3">
                        <h6 class="mb-0">Action Logs</h6>
                      </div>
                      <div class="card-body p-3">
                        <ul class="list-group">
                          {% for log in logs %}

                            <li class="list-group-item border-0 d-flex align-items-center px-0 mb-2 pt-0">
                              <div class="avatar me-3">
                                <img src="{% if log.log_author.image %}{{ log.log_author.image.url }}{% endif %}" alt="{{ log.log_author.get_full_name|capfirst }}" width="50px" height="50px" style="object-fit: cover;" class="border-radius-lg shadow">
                              </div>
                              <div class="d-flex align-items-start flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ log.log_author.get_full_name|capfirst }}</h6>
                                <p class="mb-0 text-xs">change status from <strong>{% if log.old_status %}{{ log.old_status }}{% else %}-----{% endif %}</strong> to <strong>{% if log.new_status %}{{ log.new_status }}{% else %}-----{% endif %}</strong>.</p>
                                <p class="mb-0 text-xs">{{ log.created_at|date:"j M, Y, H:i" }}</p>
                              </div>
                            </li>

                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>

                </div>
              </div>

{% comment %} ***************************************************************************** {% endcomment %}
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.media }}

                {% if form.errors %}
                  <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form_errors">
                      {% for key, value in form.errors.items %}
                        <strong>{{ value }}</strong>
                      {% endfor %}
                    </div>
                    {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> {% endcomment %}
                  </div>
                {% endif %}

                <div class="row">

                  <div class="col-md-4 mx-5">
                    <!-- Task Status -->
                    <div class="input-group input-group-outline mb-3 mt-3 focused is-focused">
                      <label for="{{ form.task_status.id_for_label }}" class="form-label">Task Status</label>
                      {{ form.task_status }}
                    </div>
                  </div>
                </div>

                <div class=" mx-5">
                  <!-- Submit button -->
                  <button type="submit" class="btn btn-primary">Save Task</button>
                </div>

              </form>

            </div>
          </div>
        </div>
      </div>

{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_to_member, #id_cc_member, #id_task_category').select2();
    });
</script>
{% endblock %}