Core/urls.py
from django.urls import path
from .views import InboxView, ProfileView


urlpatterns = [
    path('', InboxView.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Account.urls")),
    path('', include("Core.urls")),
    path('', include("Task.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from services.uploader import Uploader
from services.mixins import DateMixin
from ckeditor.fields import RichTextField
from datetime import date



class CustomUserManager(BaseUserManager):
    def create_user(self, email=None, FIN=None, number=None, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")

        user = self.model(email=self.normalize_email(email), FIN=FIN, number=number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email=None, FIN=None, number=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        if email is None:
            raise ValueError('The Email field must be set for superusers.')

        return self.create_user(email, FIN, number, password, **extra_fields)


class Department(DateMixin):
    title = models.CharField(max_length=255)
    description = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Department'


class Account(AbstractUser):
    user_status = (
        ('Head of Department', 'Head of Department'),
        ('Assistant', 'Assistant'),
        ('Staff Department', 'Staff Department')
    )
    status = models.CharField(max_length=20, choices=user_status, null=True, blank=True)
    FIN = models.CharField(max_length=21, unique=True)
    email = models.EmailField(unique=True, max_length=254)
    number = models.CharField(max_length=20)
    image = models.ImageField(upload_to=Uploader.user_image, null=True, blank=True, max_length=255)
    birthday = models.DateField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='user_department', null=True, blank=True)
    first_time_login = models.BooleanField(default=True)

    username = None


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['FIN', 'number']

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):

        # Convert FIN to string
        fin_str = str(self.FIN)
        # Set the password to FIN if it's not already set
        if not self.password:
            self.set_password(fin_str)

        super().save(*args, **kwargs)

    # Your custom function to calculate age
    def calculate_age(self):
        if self.birthday:
            today = date.today()
            age = today.year - self.birthday.year - ((today.month, today.day) < (self.birthday.month, self.birthday.day))
            return age
        return None

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Account'

Core/models.py
from django.db import models
from Account.models import Account
from services.mixins import DateMixin



class MemberTaskStatistic(DateMixin):
    member = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='send_statistic_author')
    sent_task_count = models.PositiveIntegerField(default=0)
    to_task_count = models.PositiveIntegerField(default=0)
    cc_task_count = models.PositiveIntegerField(default=0)
    forwarded_task_count = models.PositiveIntegerField(default=0)
    assigned_task_count = models.PositiveIntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.member.get_full_name()

    class Meta:
        verbose_name = 'Member Task Statistic'
        verbose_name_plural = 'Member Task Statistic'

Core/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


# Account Edit Form
class AccountEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['image', 'bio', 'number']
        widgets = {
            'image' : forms.ClearableFileInput(
                attrs={
                    'type' : 'file',
                    'class' : 'form-control',
                }
            ),
            'bio' : forms.Textarea(
                attrs={
                    'class' : 'form-control',
                    'rows' : 7
                }
            ),
            'number' : forms.TextInput(
                attrs={
                    'class' : 'form-control',
                    'type' : 'text'
                }
            )
        }

Core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from Account.models import Account
from .models import MemberTaskStatistic
from .forms import AccountEditForm
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from datetime import timedelta
from django.utils import timezone



class InboxView(LoginRequiredMixin, ListView):
    model = MemberTaskStatistic
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        today = timezone.now().date()
        yesterday = today - timedelta(days=1)

        today_statistic = MemberTaskStatistic.objects.filter(member=self.request.user, created_at__date=today).first()
        yesterday_statistic = MemberTaskStatistic.objects.filter(member=self.request.user, created_at__date=yesterday).first()

        if today_statistic:
            if yesterday_statistic and yesterday_statistic.sent_task_count != 0:
                percent_change = ((today_statistic.sent_task_count - yesterday_statistic.sent_task_count) / yesterday_statistic.sent_task_count) * 100
            else:
                percent_change = 100
            context["percent_sent_task"] = percent_change

            if yesterday_statistic and yesterday_statistic.forwarded_task_count != 0:
                percent_change = ((today_statistic.forwarded_task_count - yesterday_statistic.forwarded_task_count) / yesterday_statistic.forwarded_task_count) * 100
            else:
                percent_change = 100
            context["percent_forwarded_task"] = percent_change

            if yesterday_statistic and yesterday_statistic.assigned_task_count != 0:
                percent_change = ((today_statistic.assigned_task_count - yesterday_statistic.assigned_task_count) / yesterday_statistic.assigned_task_count) * 100
            else:
                percent_change = 100
            context["percent_assigned_task"] = percent_change

            if yesterday_statistic and yesterday_statistic.to_task_count != 0:
                percent_change = ((today_statistic.to_task_count - yesterday_statistic.to_task_count) / yesterday_statistic.to_task_count) * 100
            else:
                percent_change = 100
            context["percent_to_task"] = percent_change

            if yesterday_statistic and yesterday_statistic.cc_task_count != 0:
                percent_change = ((today_statistic.cc_task_count - yesterday_statistic.cc_task_count) / yesterday_statistic.cc_task_count) * 100
            else:
                percent_change = 100
            context["percent_cc_task"] = percent_change

            context["todays_task"] = today_statistic

        # Weekly statistic
        this_week_start = today - timedelta(days=today.weekday())
        this_week_end = this_week_start + timedelta(days=6)

        last_week_start = this_week_start - timedelta(days=7)
        last_week_end = last_week_start + timedelta(days=6)

        last_week_statistic = MemberTaskStatistic.objects.filter(member=self.request.user, created_at__date__range=[last_week_start, last_week_end])
        this_week_statistic = MemberTaskStatistic.objects.filter(member=self.request.user, created_at__date__range=[this_week_start, this_week_end])

        if this_week_statistic:
            this_week_sent_count = sum([stat.sent_task_count for stat in this_week_statistic])
            context["this_week_sent_count"] = this_week_sent_count
            last_week_sent_count = sum([stat.sent_task_count for stat in last_week_statistic])

            if last_week_sent_count != 0:
                percent_change = ((this_week_sent_count - last_week_sent_count) / last_week_sent_count) * 100
            else:
                percent_change = 100

            context["percent_sent_week"] = percent_change


            this_week_to_count = sum([stat.to_task_count for stat in this_week_statistic])
            context["this_week_to_count"] = this_week_to_count
            last_week_to_count = sum([stat.to_task_count for stat in last_week_statistic])

            if last_week_to_count != 0:
                percent_change = ((this_week_to_count - last_week_to_count) / last_week_to_count) * 100
            else:
                percent_change = 100

            context["percent_to_week"] = percent_change


            this_week_cc_count = sum([stat.cc_task_count for stat in this_week_statistic])
            context["this_week_cc_count"] = this_week_cc_count
            last_week_cc_count = sum([stat.cc_task_count for stat in last_week_statistic])

            if last_week_cc_count != 0:
                percent_change = ((this_week_cc_count - last_week_cc_count) / last_week_cc_count) * 100
            else:
                percent_change = 100

            context["percent_cc_week"] = percent_change

            this_week_forwarded_count = sum([stat.forwarded_task_count for stat in this_week_statistic])
            context["this_week_forwarded_count"] = this_week_forwarded_count
            last_week_forwarded_count = sum([stat.forwarded_task_count for stat in last_week_statistic])

            if last_week_forwarded_count != 0:
                percent_change = ((this_week_forwarded_count - last_week_forwarded_count) / last_week_forwarded_count) * 100
            else:
                percent_change = 100

            context["percent_forwarded_week"] = percent_change

            this_week_assigned_count = sum([stat.assigned_task_count for stat in this_week_statistic])
            context["this_week_assigned_count"] = this_week_assigned_count
            last_week_assigned_count = sum([stat.assigned_task_count for stat in last_week_statistic])

            if last_week_assigned_count != 0:
                percent_change = ((this_week_assigned_count - last_week_assigned_count) / last_week_assigned_count) * 100
            else:
                percent_change = 100

            context["percent_assigned_week"] = percent_change

            context["this_week_statistic"] = this_week_statistic

        return context


class ProfileView(LoginRequiredMixin, View):
    model = Account
    template_name = 'profile.html'

    def get_context_data(self):
        context = {}
        context["account_user"] = Account.objects.filter(id=self.request.user.pk).first()
        return context

    def get(self, request, *args, **kwargs):
        form = AccountEditForm(instance=request.user)
        return render(request, self.template_name, {**self.get_context_data(), 'form': form})

    def post(self, request, *args, **kwargs):
        form = AccountEditForm(request.POST, request.FILES)

        if form.is_valid():
            user_account = Account.objects.get(pk=request.user.pk)
            user_account.number = form.cleaned_data.get('number')
            user_account.bio = form.cleaned_data.get('bio')
            # user_account.image = form.cleaned_data.get('image')
            if form.cleaned_data.get('image'):
                user_account.image = form.cleaned_data.get('image')
            elif 'image' in form.cleaned_data and not form.cleaned_data['image'] is None:
                user_account.image = None
            user_account.save()
            messages.success(request, 'Profile changed successfully.')
            return redirect('profile')
        else:
            messages.error(request, 'Məlumatlarınız yenilənmədi')
            return redirect('profile')

Core/templates/messages.html
{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    {{ message }}
  </div>
{% endfor %}

Core/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="container-fluid px-2 px-md-4">
      <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
        <span class="mask  bg-gradient-primary  opacity-6"></span>
      </div>
      <div class="card card-body mx-3 mx-md-4 mt-n6">
        <div class="row gx-4 mb-2">
          <div class="col-auto">
            <div class="avatar avatar-xl position-relative">
              <img src="{% if account_user.image %}{{ account_user.image.url }}{% else %}{% static '' %}img/bruce-mars.jpg{% endif %}" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
            </div>
          </div>
          <div class="col-auto my-auto">
            <div class="h-100">
              <h5 class="mb-1">
                {{ account_user.first_name|capfirst }} {{ account_user.last_name|capfirst }}
              </h5>
              <p class="mb-0 font-weight-normal text-sm">
                {% if account_user.department.title %}{{ account_user.department.title|capfirst }}{% endif %} / {% if account_user.status %}{{ account_user.status|capfirst }}{% endif %}
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="row">
            <div class="col-12 col-xl-8">
              <div class="card card-plain h-100">
                <div class="card-header pb-0 p-3">
                  <div class="row">
                    <div class="col-md-8 d-flex align-items-center">
                      <h6 class="mb-0">Profile Edit</h6>
                      {% include "messages.html" %}
                    </div>
                    <div class="col-md-4 text-end">
                      <i class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Profile"></i>
                    </div>
                  </div>
                </div>
                
                <div class="card-body p-3">
                  <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                    <form method="post" class="w-100" style="display: flex; flex-direction: column;" enctype="multipart/form-data">

                      {% csrf_token %}

                      {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                          <div id="form_errors">
                            {% for key, value in form.errors.items %}
                              <strong>{{ value }}</strong>
                            {% endfor %}
                          </div>
                        </div>
                      {% endif %}

                      <div class="input-group input-group-outline mb-2 mt-2 focused is-focused">
                        <label class="form-label">Phone Number</label>
                        {{ form.number }}
                      </div>
                      <div class="input-group input-group-outline mb-2 mt-2 {% if form.bio.value %}focused is-focused{% endif %} ">
                        <label class="form-label">Biography</label>
                        {% if form.bio.value %}
                          {{ form.bio }}
                        {% else %}
                          <input type="textarea" id="id_bio" name='bio' rows="15" class="form-control" />
                        {% endif %}
                        
                      </div>

                      <div class="input-group input-group-outline mb-2 mt-2 w-60">
                        {{ form.image }}
                      </div>

                      <div class="col-lg-3 col-sm-6 col-4">
                        <button class="btn bg-gradient-success w-100 mb-0" type="submit">Edit Profile</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-12 col-xl-4">
              <div class="card card-plain h-100">
                <div class="card-header pb-0 p-3">
                  <div class="row">
                    <div class="col-md-8 d-flex align-items-center">
                      <h6 class="mb-0">Profile İnformation</h6>
                    </div>
                  </div>
                </div>
                <div class="card-body p-3">
                  <ul class="list-group">
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">FIN:</strong> &nbsp; {{ account_user.FIN }}</li>
                    <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Full Name:</strong> &nbsp; {{ account_user.first_name|capfirst }} {{ account_user.last_name|capfirst }}</li>
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Department:</strong> &nbsp; {% if account_user.department.title %}{{ account_user.department.title|capfirst }}{% endif %}</li>
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Position:</strong> &nbsp; {% if account_user.status %}{{ account_user.status|capfirst }}{% endif %}</li>
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Email:</strong> &nbsp; {{ account_user.email }}</li>
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Birthday:</strong> &nbsp; {% if account_user.birthday %}{{ account_user.birthday }} ({{ account_user.calculate_age }}){% endif %}</li>
                    <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Mobile:</strong> &nbsp; {{ account_user.number }}</li>
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

{% endblock %}